# Generated by Django 5.1.2 on 2025-04-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('CARD_GAME', 'Хөзрийн тоглоом'), ('SEQUENCE_GAME', 'Харааны санах ой'), ('CHIMP_TEST', 'дараалалын санах ой')], max_length=20)),
                ('game_name', models.CharField(default='Memory Match', max_length=100)),
                ('score', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='memoryapp.player')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
