# Generated by Django 5.1.3 on 2025-05-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('CARD_GAME', 'Хөзрийн тоглоом'), ('SEQUENCE_GAME', 'Харааны санах ой'), ('CHIMP_TEST', 'дараалалын санах ой')], max_length=20)),
                ('current_level', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('card_images', models.JSONField(default=list)),
                ('flipped_cards', models.JSONField(default=list)),
                ('matched_cards', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to='memoryapp.player')),
            ],
            options={
                'unique_together': {('player', 'game_type')},
            },
        ),
    ]
